### ISSUE TITLE
TypeError: Cannot read property 'unref' of undefined

### ISSUE THREAD

**Issue by lacker** [webtorrent/bittorrent-protocol#44]
I'm getting an error from within the bittorrent-protocol module when running a simple WebTorrent download.

```
/home/lacker/js/node_modules/bittorrent-protocol/index.js:617
    if (this._timeoutUnref && this._timeout.unref) this._timeout.unref()
                                            ^

TypeError: Cannot read property 'unref' of undefined
    at Wire._updateTimeout (/home/lacker/js/node_modules/bittorrent-protocol/index.js:617:45)
    at Wire._callback (/home/lacker/js/node_modules/bittorrent-protocol/index.js:602:52)
    at Wire._onPiece (/home/lacker/js/node_modules/bittorrent-protocol/index.js:507:10)
    at Wire._onMessage (/home/lacker/js/node_modules/bittorrent-protocol/index.js:673:21)
    at Wire._write (/home/lacker/js/node_modules/bittorrent-protocol/index.js:591:12)
    at doWrite (/home/lacker/js/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/lacker/js/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Wire.Object.<anonymous>.Writable.write (/home/lacker/js/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
```

Looks like `this._timeoutUnref` is set but `this._timeout` isn't. I'm just creating a client, calling `client.add(magnet)` on it, and waiting for the "done" event on the response torrent.

**Comment by feross** [comment]
@lacker What environment are you running this in? It looks like `setTimeout()` is returning `undefined` for you, which should not happen. This is the full code:

```js
    this._timeout = setTimeout(() => this._onTimeout(), this._timeoutMs)
    if (this._timeoutUnref && this._timeout.unref) this._timeout.unref()
```

**Comment by lacker** [comment]
Ah, I should have updated this issue too. I tracked it down, it's from within a unit test that uses jest, which in turn uses jsdom for its "window" object, during the cleanup phase. The jsdom window `setTimeout()` returns `undefined` after the window has been closed, which I believe is incorrect behavior, and I reported this against jsdom here:

**Comment by feross** [comment]
Thanks for following up, @lacker. We use `setTimeout` all over the codebase. I'd rather not scatter a hack across the codebase to solve a bug in `jsdom`. I know this probably isn't what you wanted to hear, but I don't think WebTorrent is the right place to fix this.
